### ISSUE TITLE
Tests report 401 Unauthorized

### ISSUE THREAD

**Issue by garemoko** [adlnet-archive/grail-issue-tracker#13]
There are a number of tests that report a response of 401 unauthorized. I tested the first one and was not able to replicate:

(failed) Any LRS API that accepts a POST request can accept a POST request with a single query string parameter named "method" on that request (Communication 1.3.s3.b2) 
RejectionError: expected 200 "OK", got 401 "Unauthorized"

I'm not going to test the other items that claim 401 "Unauthorized"until this one is resolved.

**Comment by garemoko** [comment]
Here's an example of a section with tests that fail in this way. For all the failed tests, Watershed records that the authentication header was missing. 

(failed) An LRS rejects with error code 405 Method Not Allowed to any request to an API which uses a method not in this specification **Implicit ONLY in that HTML normally does this behavior**
Retest only these requirements
(failed) should fail with statement "DELETE" 
Error: expected 405 "Method Not Allowed", got 401 "Unauthorized"
(failed) should fail with activities "DELETE" 
Error: expected 405 "Method Not Allowed", got 401 "Unauthorized"
(passed) should fail with activities "POST"
(passed) should fail with activities "PUT"
(failed) should fail with agents "DELETE" 
Error: expected 405 "Method Not Allowed", got 401 "Unauthorized"
(passed) should fail with agents "POST"
(passed) should fail with agents "PUT"

**Comment by cr8onski** [comment]
I'm still looking into the first issue.

On the second, I have a fix and would like to run it against Watershed.  Is that a possibility?

**Comment by garemoko** [comment]
@cr8onski sure, can you email andrew.downes@watershedlrs.com and let me know what you need?

**Comment by cr8onski** [comment]
second part fixed in https://github.com/adlnet/lrs-conformance-test-suite/commit/7cd322d30e1bcb8af8f0f60d835c86702213ad14

**Comment by garemoko** [comment]
I'm still seeing three tests with missing authentication headers under "An LRS rejects with error code 400 Bad Request, a Request which does not use a "X-Experience-API-Version" header name to any Resource except the About Resource":

* should fail when Statement GET without header "X-Experience-API-Version"
* should fail when Statement POST without header "X-Experience-API-Version"
* should fail when Statement PUT without header "X-Experience-API-Version"

**Comment by garemoko** [comment]
Also several tests under Alternate Request Syntax Requirements. In this case there is an Authorization header but it has the value "Basic". Really this should be a form parameter anyway. 

* An LRS rejects a new Request in the same way for violating rules of this document as it would a normal Request
* Any LRS Resource that accepts a POST request can accept a POST request with a single query string parameter named "method" on that request
* An LRS will reject any request sending content which does not have a form parameter with the name of "content"
* An LRS will treat the content of the form parameter named "content" as a UTF-8 String
* An LRS will reject a new Request with a form parameter named "content" if "content" is found to be binary data with error code 400 Bad Request 
* An LRS must parse the body of a Cross Origin Request and construct a new Request from it with the type of Request being the same as the value of the "method" parameter 
* An LRS will map form parameters from the body of the Cross Origin Request to the similarly named HTTP Headers in the new Request

**Comment by cr8onski** [comment]
Is anyone still having an issue with 401's in the test suite?  I believe this has been indirectly addressed by other fixes, but would like to hear this is still coming up for anyone.

**Comment by bscSCORM** [comment]
@garemoko regarding the Alternate Request Syntax specifically, as I understand it the requirement:
> An LRS will map form parameters from the body of the Cross Origin Request to the similarly named HTTP Headers in the new Request

and language:
> The Learning Record Provider MAY include any header parameters required by this specification which are expected to appear in the HTTP header as form parameters with the same names. This applies to the following parameters: Authorization, X-Experience-API-Version, Content-Type, Content-Length, If-Match and If-None-Match. It does not apply to Content-Transfer-Encoding.

Leads me to think the 401 on the alternate request syntax when authentication is included as an HTTP header is an LRS issue

However: the tests aren't complete unless they include some instances of the authorization header *only* appearing in the form data, as the LRS is required to handle that too. (I haven't noticed if that is the case or not)

**Comment by garemoko** [comment]
@bscSCORM that sounds right, though in the case I reported here, the actual authorization header value is/was wrong - literally the string "Basic" with no token.

**Comment by bscSCORM** [comment]
@garemoko @cr8onski I'm not seeing just the "Basic" header on its own now, so it looks like this probably is no longer an issue?

**Comment by garemoko** [comment]
I'm not going to get to re-test this any time soon so i'll close for now. I can re-create a ticket if it's still an issue next time I test.
